/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ui;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Hihew
 */
public class ChatRoomPanel extends javax.swing.JPanel {

    /**
     * Creates new form ChatRoomPanel
     */
    public ChatRoomPanel() {
        initComponents();
    }
    public void setImgIconUser(ImageIcon icon){
        jIconSendUserLabel.setIcon(icon);
    }
    public void setSendUsername(String name){
        jSendUsernameLabel.setText(name);
    }
    public void setMessageSend(String content){
        jMessTextField.setText(content);
    }
    
    public void setTextColor(Color c){
        jSendUsernameLabel.setForeground(c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jIconSendUserLabel = new javax.swing.JLabel();
        jMessTextField = new javax.swing.JTextField();
        jSendUsernameLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        setMaximumSize(new java.awt.Dimension(640, 46));
        setMinimumSize(new java.awt.Dimension(640, 46));
        setPreferredSize(new java.awt.Dimension(640, 46));

        jIconSendUserLabel.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jIconSendUserLabel.setForeground(new java.awt.Color(102, 102, 102));
        jIconSendUserLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ui/img/system.png"))); // NOI18N
        jIconSendUserLabel.setToolTipText("");
        jIconSendUserLabel.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jMessTextField.setEditable(false);
        jMessTextField.setBackground(new java.awt.Color(255, 255, 255));
        jMessTextField.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jMessTextField.setText("Hihew");
        jMessTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 6, 6, 6));
        jMessTextField.setOpaque(false);
        jMessTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMessTextFieldActionPerformed(evt);
            }
        });

        jSendUsernameLabel.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jSendUsernameLabel.setForeground(new java.awt.Color(102, 102, 102));
        jSendUsernameLabel.setText("Hihew");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jIconSendUserLabel)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSendUsernameLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jMessTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 533, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSendUsernameLabel)
                        .addGap(1, 1, 1)
                        .addComponent(jMessTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jIconSendUserLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jMessTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMessTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMessTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jIconSendUserLabel;
    public javax.swing.JTextField jMessTextField;
    private javax.swing.JLabel jSendUsernameLabel;
    // End of variables declaration//GEN-END:variables
}
